// src/database/db.ts
// Drizzle ORM connection using expo-sqlite

import { openDatabaseSync } from 'expo-sqlite';
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
import * as schema from './schema';
import migrations from './migrations/migrations';

// Open database synchronously (required for Drizzle)
const expoDb = openDatabaseSync('littleloom.db');

// Create Drizzle ORM instance
export const db = drizzle(expoDb, { schema });

// Migration hook for React components
export function useDatabaseMigrations() {
  return useMigrations(db, migrations);
}

// Export schema for direct access
export * from './schema';

export default db;
'''

with open('/mnt/agents/output/src_database_db.ts', 'w') as f:
    f.write(drizzle_db)

# Create the migration helper (auto-generated by drizzle-kit, but we provide a starter)
migrations_js = '''// src/database/migrations/migrations.js
// Auto-generated by drizzle-kit, do not edit manually

import journal from './meta/_journal.json';
import m0000 from './0000_initial_schema.sql';

export default {
  journal,
  migrations: {
    m0000,
  },
};
'''

with open('/mnt/agents/output/src_database_migrations_migrations.js', 'w') as f:
    f.write(migrations_js)

# Create initial migration SQL
migration_sql = '''-- Migration: 0000_initial_schema
-- Created automatically from drizzle schema

CREATE TABLE IF NOT EXISTS "babies" (
	"id"	text PRIMARY KEY NOT NULL,
	"name"	text NOT NULL,
	"avatar"	text,
	"date_of_birth"	text NOT NULL,
	"gender"	text,
	"blood_type"	text,
	"allergies"	text DEFAULT '[]',
	"medical_notes"	text,
	"parent1_id"	text,
	"parent2_id"	text,
	"created_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"is_active"	integer DEFAULT true NOT NULL,
	"sync_status"	text DEFAULT 'pending' NOT NULL
);

CREATE TABLE IF NOT EXISTS "photos" (
	"id"	text PRIMARY KEY NOT NULL,
	"uri"	text NOT NULL,
	"local_uri"	text,
	"thumbnail_uri"	text,
	"baby_id"	text,
	"date"	text NOT NULL,
	"timestamp"	integer NOT NULL,
	"type"	text DEFAULT 'daily' NOT NULL,
	"caption"	text,
	"is_favorite"	integer DEFAULT false NOT NULL,
	"is_private"	integer DEFAULT false NOT NULL,
	"is_screenshot"	integer DEFAULT false NOT NULL,
	"tags"	text DEFAULT '[]',
	"location"	text,
	"exif"	text,
	"mood"	text,
	"source"	text DEFAULT 'camera' NOT NULL,
	"backup_status"	text DEFAULT 'pending' NOT NULL,
	"faces_detected"	text DEFAULT '[]',
	"ai_tags"	text DEFAULT '[]',
	"blur_hash"	text,
	"folder"	text,
	"linked_entry_id"	text,
	"linked_entry_type"	text,
	"created_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"sync_status"	text DEFAULT 'pending' NOT NULL,
	FOREIGN KEY("baby_id") REFERENCES "babies"("id") ON DELETE set null ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "tracker_entries" (
	"id"	text PRIMARY KEY NOT NULL,
	"tracker_id"	text NOT NULL,
	"baby_id"	text NOT NULL,
	"timestamp"	integer NOT NULL,
	"title"	text,
	"data"	text DEFAULT '{}' NOT NULL,
	"notes"	text,
	"tags"	text DEFAULT '[]',
	"photo_uris"	text DEFAULT '[]',
	"location"	text,
	"mood"	text,
	"created_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"sync_status"	text DEFAULT 'pending' NOT NULL,
	FOREIGN KEY("baby_id") REFERENCES "babies"("id") ON DELETE cascade ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "photo_import_queue" (
	"id"	text PRIMARY KEY NOT NULL,
	"uri"	text NOT NULL,
	"status"	text DEFAULT 'pending' NOT NULL,
	"priority"	integer DEFAULT 0 NOT NULL,
	"source_type"	text NOT NULL,
	"detected_baby_ids"	text DEFAULT '[]',
	"ai_confidence"	real,
	"error_message"	text,
	"retry_count"	integer DEFAULT 0 NOT NULL,
	"created_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"processed_at"	text
);

CREATE TABLE IF NOT EXISTS "smart_albums" (
	"id"	text PRIMARY KEY NOT NULL,
	"title"	text NOT NULL,
	"type"	text NOT NULL,
	"icon"	text,
	"gradient"	text,
	"filter_query"	text,
	"photo_count"	integer DEFAULT 0 NOT NULL,
	"cover_photo_id"	text,
	"is_system"	integer DEFAULT false NOT NULL,
	"sort_order"	integer DEFAULT 0 NOT NULL,
	"created_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY("cover_photo_id") REFERENCES "photos"("id") ON DELETE set null ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "album_photos" (
	"album_id"	text NOT NULL,
	"photo_id"	text NOT NULL,
	"added_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY("album_id","photo_id"),
	FOREIGN KEY("album_id") REFERENCES "smart_albums"("id") ON DELETE cascade ON UPDATE no action,
	FOREIGN KEY("photo_id") REFERENCES "photos"("id") ON DELETE cascade ON UPDATE no action
);

CREATE TABLE IF NOT EXISTS "app_settings" (
	"key"	text PRIMARY KEY NOT NULL,
	"value"	text NOT NULL,
	"updated_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "scan_sessions" (
	"id"	text PRIMARY KEY NOT NULL,
	"started_at"	text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completed_at"	text,
	"photos_found"	integer DEFAULT 0 NOT NULL,
	"photos_imported"	integer DEFAULT 0 NOT NULL,
	"photos_skipped"	integer DEFAULT 0 NOT NULL,
	"status"	text DEFAULT 'running' NOT NULL,
	"error_message"	text
);

-- Indexes
CREATE INDEX IF NOT EXISTS "idx_babies_active" ON "babies" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_babies_parent" ON "babies" ("parent1_id");
CREATE INDEX IF NOT EXISTS "idx_babies_sync" ON "babies" ("sync_status");
CREATE INDEX IF NOT EXISTS "idx_photos_baby" ON "photos" ("baby_id");
CREATE INDEX IF NOT EXISTS "idx_photos_date" ON "photos" ("date");
CREATE INDEX IF NOT EXISTS "idx_photos_timestamp" ON "photos" ("timestamp");
CREATE INDEX IF NOT EXISTS "idx_photos_type" ON "photos" ("type");
CREATE INDEX IF NOT EXISTS "idx_photos_favorite" ON "photos" ("is_favorite");
CREATE INDEX IF NOT EXISTS "idx_photos_private" ON "photos" ("is_private");
CREATE INDEX IF NOT EXISTS "idx_photos_source" ON "photos" ("source");
CREATE INDEX IF NOT EXISTS "idx_photos_backup" ON "photos" ("backup_status");
CREATE INDEX IF NOT EXISTS "idx_photos_sync" ON "photos" ("sync_status");
CREATE INDEX IF NOT EXISTS "idx_photos_baby_date" ON "photos" ("baby_id","date");
CREATE INDEX IF NOT EXISTS "idx_entries_tracker" ON "tracker_entries" ("tracker_id");
CREATE INDEX IF NOT EXISTS "idx_entries_baby" ON "tracker_entries" ("baby_id");
CREATE INDEX IF NOT EXISTS "idx_entries_timestamp" ON "tracker_entries" ("timestamp");
CREATE INDEX IF NOT EXISTS "idx_entries_baby_tracker" ON "tracker_entries" ("baby_id","tracker_id");
CREATE INDEX IF NOT EXISTS "idx_entries_sync" ON "tracker_entries" ("sync_status");
CREATE INDEX IF NOT EXISTS "idx_queue_status" ON "photo_import_queue" ("status");
CREATE INDEX IF NOT EXISTS "idx_queue_priority" ON "photo_import_queue" ("status","priority");
CREATE INDEX IF NOT EXISTS "idx_albums_type" ON "smart_albums" ("type");
CREATE INDEX IF NOT EXISTS "idx_albums_system" ON "smart_albums" ("is_system","sort_order");
CREATE INDEX IF NOT EXISTS "idx_album_photos_photo" ON "album_photos" ("photo_id");

-- Seed default albums
INSERT OR IGNORE INTO "smart_albums" ("id", "title", "type", "icon", "gradient", "filter_query", "is_system", "sort_order")
VALUES 
  ('album_all', 'All Photos', 'smart', 'images', '["#667eea","#764ba2"]', '{}', 1, 0),
  ('album_favorites', 'Favorites', 'smart', 'heart', '["#f093fb","#f5576c"]', '{"isFavorite":true}', 1, 1),
  ('album_screenshots', 'Screenshots', 'smart', 'phone-portrait', '["#8b5cf6","#6366f1"]', '{"isScreenshot":true}', 1, 2),
  ('album_auto_import', 'Auto Imported', 'smart', 'sync', '["#10b981","#06b6d4"]', '{"source":"auto_import"}', 1, 3),
  ('album_vault', 'Private Vault', 'smart', 'shield', '["#1e293b","#0f172a"]', '{"isPrivate":true}', 1, 4),
  ('album_milestones', 'Milestones', 'smart', 'trophy', '["#f59e0b","#ef4444"]', '{"type":"milestone"}', 1, 5);
'''

with open('/mnt/agents/output/src_database_migrations_0000_initial_schema.sql', 'w') as f:
    f.write(migration_sql)

# Create meta journal
journal_json = '''{
  "version": "7",
  "dialect": "sqlite",
  "entries": [
    {
      "idx": 0,
      "version": "7",
      "when": 1700000000000,
      "tag": "0000_initial_schema",
      "breakpoints": true
    }
  ]
}
