// src/database/migrations/migrations.js
// Auto-generated by drizzle-kit generate
// If this file is missing, run: npx drizzle-kit generate

// Fallback journal for first run
const journal = {
  version: "7",
  dialect: "sqlite",
  entries: []
};

// Try to load generated journal
try {
  const generatedJournal = require('./meta/_journal.json');
  Object.assign(journal, generatedJournal);
} catch (e) {
  console.warn('[Migrations] No journal found. Run: npx drizzle-kit generate');
}

// Collect all migration modules
const migrationModules = {};

// Auto-discover migration files (m0000, m0001, etc.)
const migrationContext = require.context('./', false, /^\\d{4}_.+\\.sql$/);

migrationContext.keys().forEach((key) => {
  const match = key.match(/(m\\d{4})_.+\\.sql$/);
  if (match) {
    migrationModules[match[1]] = migrationContext(key);
  }
});

export default {
  journal,
  migrations: migrationModules,
};